[package]
name = "coding100"
version = "0.1.0"
authors = ["Kazuki Yoshida <idkphys.030zzz@gmail.com>"]
edition = "2018"

[dependencies]
proconio = "0.4.1"

[[bin]]
name = "no001"
path = "src/no001.rs"

[[bin]]
name = "no002"
path = "src/no002.rs"
